### ISSUE TITLE
Participation in developing the existential operator proposal Babel plugin

### ISSUE THREAD

**Issue by hzoo** [facebookincubator/idx#2]
Feel free to close the issue (since this is about the existential proposal), but I wanted to check in/ask if FB would be willing to help with the development of the actual babel plugin given it's Stage 1 now (https://github.com/babel/babylon/issues/328).

Aside: happy to see the use of preset-env and lerna 😄

**Comment by yungsters** [comment]
I've shared this call for help with engineers internally at Facebook. Thanks for raising this opportunity! (I actually didn't realize that it was already Stage 1.)

My first time using `preset-env` and `lerna`. I hope I did it right. 😄

**Comment by hzoo** [comment]
Yep! We're working with @gisenberg (Gabriel Isenberg) who is the new champion for this. We also have a slack room for it https://babeljs.slack.com/messages/proposal-opt-chaining

**Comment by hzoo** [comment]
Babylon PR is at https://github.com/babel/babylon/pull/545

**Comment by hzoo** [comment]
FYI https://github.com/babel/proposals/issues/18 - proposal is Stage 1 and in one of the 7.x alpha releases
