### ISSUE TITLE
idx() callbacks may only access properties on the callback parameter!

### ISSUE THREAD

**Issue by xareelee** [facebookincubator/idx#24]
I've reported this issue on flowtype: https://github.com/facebook/flow/issues/4729

I also create an issue here.

---

The following code raises a [flowtype](https://flowtype.org/) error when using [idx](https://github.com/facebookincubator/idx) with [immutable.js](https://github.com/facebook/immutable-js/):

```js
// `state` is obtained from redux store
// `state.user` is an immutable object; you need to use `getIn()` to access properties
const token = idx(state, _ => _.user.getIn(['userInfo', 'token']));
```

The flowtype shows the error:

```
 81:   const countryCode = idx(state, _ => _.country.getIn(['selectCountry', 'countryCode']));
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. idx() callbacks may only access properties on the callback parameter!
```

I need to change code to this to suppress flowtype warnings:

```js
const tokenS = idx(state, _ => _.user.getIn);
const token = (tokenS) ? tokenS(['userInfo', 'token']) : undefined;
```

It makes no sense to write such code.

**Comment by yungsters** [comment]
Call expressions are no longer supported from within `idx`. Obsoleted by v2.0.0.
