### ISSUE TITLE
Can't make babel-plugin-idx works with async function

### ISSUE THREAD

**Issue by didierfranc** [facebookincubator/idx#4]
## Description

Everything is working fine until I use idx inside async function

```js
const obj = { a: 0, b: { c: 1 } }

const Working = () => {
  idx(obj, _ => _.b.c)
}

const notWorking = async () => {
  idx(obj, _ => _.b.c)
}

```

### I'm getting this :
<img width="1084" alt="capture d ecran 2017-03-16 a 11 12 12" src="https://cloud.githubusercontent.com/assets/14132464/23991408/8ff7f132-0a39-11e7-92ed-10e788a9fbbd.png">

### babel config :
```json
"babel": {
    "presets": [
      [
        "es2015",
        {
          "modules": false
        }
      ],
      "react",
      "stage-0"
    ],
    "plugins": [
      "idx",
      [
        "transform-runtime",
        {
          "helpers": false,
          "polyfill": false
        }
      ]
    ]
  }
```

**Comment by didierfranc** [comment]
cc @fbonniec

**Comment by yungsters** [comment]
Looks like [`t.isArrowFunctionExpression`](https://github.com/facebookincubator/idx/blob/master/packages/babel-plugin-idx/src/babel-plugin-idx.js#L79) might only be returning true for non-async functions (if I'm reading [babel-types/README.md](https://github.com/babel/babel/blob/67ed224df0b3165510cf94f9532422384f5e5ec0/packages/babel-types/README.md#arrowfunctionexpression) correctly).

I would most welcome a PR if you're up for it!
