### ISSUE TITLE
Flow cannot resolve module idx

### ISSUE THREAD

**Issue by grundiss** [facebookincubator/idx#48]
```
Cannot resolve module idx.

     1│ // @flow
     2│ import idx from 'idx';
     3│ import * as React from "react";
     4│ import {execute} from 'graphql/execution';
     5│ import {parse} from 'graphql/language';
```

My packages versions are:
```
"babel": "^6.23.0",
"babel-plugin-idx": "^2.2.0",
"flow-bin": "^0.72.0",
```

Do you guys have any idea what the problem might be?

**Comment by TrySound** [comment]
@grundiss Do you have `idx` in your node_modules?

**Comment by grundiss** [comment]
I didn't have (facepalm). Probably, missunderstood the installation process and installed only babel-plugin.
Problem solved, thank you!
