### ISSUE TITLE
idx doesn't detect TypeErrors in german IE

### ISSUE THREAD

**Issue by keesvanlierop** [facebookincubator/idx#51]
Related to #46 , A german error can look like this:

Die Eigenschaft "addresses" eines undefinierten oder Nullverweises kann nicht abgerufen werden.

This does not pass the regex test and therefore gets thrown in the console.

**Comment by petetnt** [comment]
Same with Finnish IE11: The error message in finnish is `Määrittämättömän tai tyhjän viittauksen ominaisuutta...` for `Unable to get property 'biz' of undefined or null reference`

**Comment by petetnt** [comment]
As a workaround the babel transform and the macro (https://github.com/dralletje/idx.macro) work well because the values get precomputed!

**Comment by yungsters** [comment]
I've updated the `README.md` to mention that `babel-plugin-idx` is critical to correct behavior of `idx`. Thanks for reporting this.
