### ISSUE TITLE
Firefox nightly - idx fails to match TypeErrors

### ISSUE THREAD

**Issue by ArnaudRinquin** [facebookincubator/idx#53]
TypeErrors in Firefox nightly do not pass [the `undefinedPattern` and `nullPattern` tests](https://github.com/facebookincubator/idx/blob/master/packages/idx/src/idx.js#L65).

It's easily reproducible:

* Go to this [JSFiddle](https://jsfiddle.net/z5f2rnxk/5/)
* Open the Debugger and check `Pause on exception`
* Observe that the error is rethrown while it should be handled on line 65.

Screenshot:

<img width="1224" alt="screen shot 2018-08-27 at 10 50 30" src="https://user-images.githubusercontent.com/228886/44651081-a923c280-a9e8-11e8-83ae-688004f32c02.png">

This is due to TypeErrors messages in Firefox nightly being different from regular Firefox, see the same example in regular Firefox: 

<img width="218" alt="screen shot 2018-08-27 at 10 59 59" src="https://user-images.githubusercontent.com/228886/44651052-91e4d500-a9e8-11e8-9c8e-2f890f2aad67.png">

**Comment by kud** [comment]
Ha! I'm not the only one!

I'm doing something like

```
const simpleQueryString = idx(rawQuery, _ => _.query.simple_query_string)
```

and I've got 

```
TypeError: "_.query is undefined, can't access property "simple_query_string" of it"
```

only on firefox nightly (fresh profile or not), no trouble on firefox _classic_ and chrome and canary.

**Comment by hackel** [comment]
Also happening on Firefox 63.0b2 (Developer edition).  This basically renders this package entirely unusable.

**Comment by ArnaudRinquin** [comment]
Yeah well, I think the foundations of this package is a bit broken: it relies on the error messages which are far from being reliable.

We eventually decided not to use it.

**Comment by kud** [comment]
Same here. I liked the concept of the lib but how it's done, it's not possible to use it.

**Comment by yungsters** [comment]
As mentioned in the `README.md` under “Babel Transform”:

> The idx runtime function exists for the purpose of illustrating the expected behavior and is not meant to be executed. The idx function is used in conjunction with a Babel plugin that replaces it with better performing code.

The implementation of `idx` in this package is not meant to be executed anywhere.

**Comment by kud** [comment]
In this case, be more precise on the README maybe. Because having this information only in the babel section means if you don't have babel or don't want to use it via babel, you won't read this part.
