### ISSUE TITLE
[TS] v2.5.0 DeepRequired generic breaks input.focus()

### ISSUE THREAD

**Issue by sseppola** [facebookincubator/idx#60]
After upgrading to v2.5.0 I get the following error:
![screen shot 2018-11-23 at 16 39 54](https://user-images.githubusercontent.com/4065840/48951508-15a65300-ef3f-11e8-850b-2a15543ca68d.png)

Context:
![screen shot 2018-11-23 at 16 39 36](https://user-images.githubusercontent.com/4065840/48951555-48504b80-ef3f-11e8-86a6-9b42eec291a3.png)

**Comment by yungsters** [comment]
@mohsen1, any ideas?

**Comment by sseppola** [comment]
What improvement does the current definition give over the previous definition?

By the looks of it, now lets me write accessors without using `!` in places where something could be null or undefined, eg:
```
const id = idx(this.props, _ => _.card!.id);
```

I'm by no means an expert here, but it seems like it thinks the function is an object [here](https://github.com/facebookincubator/idx/compare/v2.4.0...v2.5.0#diff-b31f1ed03010af5bfecd05f94de3d8c5R28), so perhaps we could check if T is a function type first

**Comment by mohsen1** [comment]
I'm looking into this. Something like this will fix it:

```ts
/**
 * DeepRequired
 * Required that works for deeply nested structure
 */
type DeepRequired<T> = T extends any[]
  ? DeepRequiredArray<T[number]>
  : T extends (...args: any[]) => infer R
    ? (...args: any[]) => DeepRequired<R>
    : T extends object ? DeepRequiredObject<T> : T;

```
