### ISSUE TITLE
Replace `NonUndefinedOrnNull` with TypeScript standard type `NonNullable`

### ISSUE THREAD

**Issue by malash** [facebookincubator/idx#64]
Replace `NonUndefinedOrnNull` with TypeScript standard type `NonNullable`.

https://github.com/facebookincubator/idx/blob/master/packages/idx/src/idx.d.ts#L5

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#predefined-conditional-types

@mohsen1

**Comment by mohsen1** [comment]
Yes they are exactly the same. 

https://github.com/Microsoft/TypeScript/blob/3e4c5c95abd515eb9713b881d27ab3a93cc00461/src/lib/es5.d.ts#L1439

Happy to review a PR for that
