### ISSUE TITLE
Upgrade to latest version of Flow

### ISSUE THREAD

**Issue by nickluger** [facebookincubator/idx#68]
### Upgrade to latest version of Flow

The current version: `0.89.0`.
The version used here: `^0.73.0`

**Comment by yungsters** [comment]
Thanks! I am recovering from eye surgery and don’t feel comfortable enough with cutting a new release, but will do so as soon as I can (in about a week’s time).

Unless someone else beats me to it…

**Comment by yungsters** [comment]
I incorrectly thought this was a pull request... :(

If anyone coming across this wants to send one, I'd be down to merge and publish a new release. 👍

**Comment by yungsters** [comment]
Upgraded in https://github.com/facebookincubator/idx/commit/978fdaaa9acb4fffc37c3a5c63e5523d544deedd.
