### ISSUE TITLE
`UnboxDeepRequired doesn't support enum type.

### ISSUE THREAD

**Issue by malash** [facebookincubator/idx#78]
```ts
enum MyEnum {
  'a' = 'a',
  'b' = 'b',
}
type MyType = {
  enum: MyEnum;
};
const e: MyEnum | null | undefined = idx({} as MyType, _ => _.enum);
```

Got:
```
Type 'IDXOptional<string>' is not assignable to type 'MyEnum | null | undefined'.
  Type 'string' is not assignable to type 'MyEnum | null | undefined'.ts(2322)
```

Because `idx`s return type is `string | null | undefined` instead of `MyEnum | null | undefined`

Related PR: https://github.com/facebookincubator/idx/pull/76

@mohsen1 @brieb @yungsters

**Comment by mohsen1** [comment]
I wonder if it's possible to narrow to your enum type before string without having access to that `MyEnum` type.

Don't forget that `idx` is a generic and you can always provide the type argument directly instead of relying on type inference. 

I'll look into this later this week.
